title: Andre Hora (DCC/UFMG)
description: "Software Testing, Software Evolution, Software Maintenance, Mining Software Repositories"
logo: andre-hora.png
theme: jekyll-theme-minimal
github:
  is_project_page: false
