title: Andre Hora (DCC/UFMG)
description: Research interests: Software Evolution, Software Maintenance, Software Testing, Mining Software Repositories
logo: andre-hora.png
theme: jekyll-theme-minimal
