title: Andre Hora (DCC/UFMG)
description: Software Evolution, Software Maintenance, Software Testing, Mining Software Repositories
logo: andre-hora.png
theme: jekyll-theme-minimal
github:
  is_project_page: false

platforms:
  - name: GitHub
    link: https://github.com/
